class InvoiceProcessor {

    public void generateInvoice(String customer, double amount) {
        double finalAmount = calculateTotal(amount);
        System.out.println("Customer: " + customer);
        System.out.println("Amount: " + finalAmount);
    }

    protected void display() {
        System.out.println("Invoice generated by InvoiceProcessor");
    }

    private double calculateTotal(double amount) {
        return amount + 50;
    }

    public void accessPrivate(double amount) {
        double total = calculateTotal(amount);
        System.out.println("Total (with charges): " + total);
    }
}

class RetailInvoice extends InvoiceProcessor {

    @Override
    public void generateInvoice(String customer, double amount) {
        double discount = amount * 0.1;
        double finalAmount = amount - discount;

        System.out.println("Customer: " + customer);
        System.out.println("Retail Amount (after discount): " + finalAmount);
    }

    @Override
    protected void display() {
        System.out.println("Invoice generated by RetailInvoice");
    }

    public double calculateTotal(double amount) {
        return amount;
    }
}

public class Bill {
    public static void main(String[] args) {

        InvoiceProcessor ip = new InvoiceProcessor();
        ip.generateInvoice("Alice", 1000);
        ip.display();
        ip.accessPrivate(1000);

        System.out.println();

        RetailInvoice ri = new RetailInvoice();
        ri.generateInvoice("Bob", 1000);
        ri.display();

        System.out.println();

        InvoiceProcessor ref = new RetailInvoice();
        ref.generateInvoice("Charlie", 1000);
        ref.display();
        ref.accessPrivate(1000);
    }
}